unique_ids:
  assets:
    standard-page.html: UJNO6TGDGSRHUKILOAIU7GV4LWFJFTWI
    theme.css: 5T5L7HNCEZN33BCFYMCCRBZHB27BUG3H
  forms:
    Form1: EDAC3P5BBZ2X7BXNEJZQWLQWKVADYGD6
  modules: {}
  scripts: {}
  server_modules: {}
